<?php

/**
 * @file
 * Module file for jira service desk integration.
 */

/**
 * Implements hook_permission().
 */
function jsd_widget_permission() {
  return array(
    'view jsd widget' => array(
      'title' => t('View JSD Widget'),
      'description' => t('Allow access to view the Jira Service Desk widget.'),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function jsd_widget_block_info() {
  $blocks['jsd_widget'] = array(
    'info' => t('Jira Service Desk Widget'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function jsd_widget_block_configure($delta = '') {
  $form = array();

  switch($delta) {
    case 'jsd_widget' :
      $form['jsd_widget_data_key'] = array(
        '#type' => 'textfield',
        '#title' => t('Data Key'),
        '#size' => 60,
        '#description' => t('The data-key value from the JSD Widget settings.'),
        '#default_value' => variable_get('jsd_widget_data_key', NULL),
      );

      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function jsd_widget_block_save($delta = '', $edit = array()) {
  switch($delta) {
    case 'jsd_widget' :
      variable_set('jsd_widget_data_key', $edit['jsd_widget_data_key']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function jsd_widget_block_view($delta = '') {
  $block = array();

  switch($delta) {
    case 'jsd_widget' :
      if (user_access('view jsd widget')) {
        $block['content'] = jsd_widget_get_block_view();
      }
      break;
  }

  return $block;
}

/**
 *  Build the jira service desk block.
 *
 * @return array
 *   returns a renderable service desk widget block.
 */
function jsd_widget_get_block_view() {

  $data_key = variable_get('jsd_widget_data_key', NULL);

  $block = array(
    'message' => array(
      '#type' => 'markup',
      '#markup' => '<script data-jsd-embedded data-key="' . check_plain($data_key) . '" data-base-url="https://jsd-widget.atlassian.com" src="https://jsd-widget.atlassian.com/assets/embed.js"></script>',
    ),
  );
  return $block;
}
