<?php

/**
 * Implements hook_block_info().
 */
function jsd_widget_block_info() {
  $blocks['jsd_widget'] = array(
    // The name that will appear in the block list.
    'info' => t('Jira Service Desk Widget'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function jsd_widget_block_configure($delta = '') {
  $form = array();
  
  switch($delta) {
    case 'jsd_widget' :
      // Text field form element
      $form['widget_data_key'] = array(
        '#type' => 'textfield',
        '#title' => t('Data Key'),
        '#size' => 60,
        '#description' => t('The data-key value from the JSD Widget settings.'),
        '#default_value' => variable_get('widget_data_key', t('')),
      );

      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function jsd_widget_block_save($delta = '', $edit = array()) {
  switch($delta) {
    case 'jsd_widget' :
      // Saving the text value.     
      variable_set('widget_data_key', $edit['widget_data_key']);

      break;
  }
}

/**
 * Implements hook_block_view().
 */
function jsd_widget_block_view($delta='') {
  $block = array();
  
  switch($delta) {
    case 'jsd_widget' :
      $block['content'] = jsd_widget_view();
      break;
  }
  
  return $block;
}

/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a renderable array of block content.
 */
function jsd_widget_view() {
  $block = array();

  // Capture WYSIWYG text from the variable
  $data_key = variable_get('widget_data_key');

  // Block output in HTML with div wrapper
  $block = array(
    'message' => array(
      '#type' => 'markup',
      '#markup' => t('<script data-jsd-embedded data-key="' . $data_key . '" data-base-url="https://jsd-widget.atlassian.com" src="https://jsd-widget.atlassian.com/assets/embed.js"></script>'),
      '#suffix' => '',
    ),
  );
  return $block;
}
